#!/bin/sh

case "$1" in
	tor)
		/etc/init.d/ferm start
		cp -f /usr/local/share/heads/sources.list.tor /etc/apt/sources.list
		echo "nameserver 127.0.0.1" > /etc/resolv.conf
		sed 's/firefox-esr.desktop/tbb.desktop/' -i \
			/home/luther/.config/lxpanel/default/panels/panel
		ln -snf /usr/share/xul-ext/torbirdy \
			/usr/lib/thunderbird/extensions/castironthunderbirdclub@torproject.org
		git checkout -- /home/luther/.electrum/config
		cp -f /usr/local/share/heads/dirmngr.conf.tor /home/luther/.gnupg/dirmngr.conf
		git checkout -- /home/luther/.config/hexchat/hexchat.conf
		;;
	vpn)
		/etc/init.d/ferm stop
		cp -f /usr/local/share/heads/sources.list.vpn /etc/apt/sources.list
		echo "nameserver 208.67.222.222" > /etc/resolv.conf
		sed 's/tbb.desktop/firefox-esr.desktop/' -i \
			/home/luther/.config/lxpanel/default/panels/panel
		rm -f /usr/lib/thunderbird/extensions/castironthunderbirdclub@torproject.org
		rm -f /home/luther/.electrum/config
		cp -f /usr/local/share/heads/dirmngr.conf.vpn /home/luther/.gnupg/dirmngr.conf
		rm -f /home/luther/.config/hexchat/hexchat.conf
		;;
esac
